In [ ]:
%pip install matplotlib
%pip install phasespace

In [1]:
import phasespace as phsp
import numpy as np
m0 = 5000
m1 = 200
m2 = 1000
m3 = 998
m4 = 400
m5 = 123

# arbitrary masses, since it does not really matter, if the particles do exist or not
# Also I couldn't remermber masses for particles, so here we go

weights, p = phsp.nbody_decay(m0, [m1, m2, m3, m4, m5]).generate(1)


global_momenta = {
    i + 1: np.array(p[f"p_{i}"])
        for i in range(5)
}

2024-06-21 15:12:26.385505: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-21 15:12:26.386532: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-21 15:12:26.391495: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-21 15:12:26.438187: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-21 15:12:27.442831: W tensorflow/compiler/tf2tensorrt/utils/py_uti

In [6]:
import numpy as np
from decayangle.lorentz import LorentzTrafo
from decayangle.decay_topology import Topology, TopologyCollection
from decayangle.config import config as cfg
import matplotlib.pyplot as plt


topology = Topology(root=0, decay_topology=(((2,(4, 5)),1),3))
reference = Topology(root=0, decay_topology=(((3,(2, 5)),1),4))

tc = TopologyCollection(0, [1,2,3,4,5])
print(topology)
print(reference)

topology = tc.filter((1,2), (4,3))[0]

result_full = reference.relative_wigner_angles(topology, global_momenta)

result_other = reference.relative_wigner_angles(topology, global_momenta, use_other=True)

from decayangle.kinematics import build_2_2
for k, v in result_full.items():
    print(k)
    res1 = np.array(list(val[0] for val in v))
    res2 = np.array(list(val[0] for val in result_other[k]))
    print(res1)
    print(res2)
    print(np.fmod(res1 - res2, 4*np.pi))
    print(np.sum(build_2_2(0,0,0,*res1) - build_2_2(0,0,0,*res2)))

result = result_full[2]

Topology: ( 0 -> ( (1, 2, 4, 5) -> ( (2, 4, 5) -> ( (4, 5) -> 4, 5 ), 2 ), 1 ), 3 )
Topology: ( 0 -> ( (1, 2, 3, 5) -> ( (2, 3, 5) -> ( (2, 5) -> 2, 5 ), 3 ), 1 ), 4 )
2
[-3.09184253  1.88201257 -2.2548422 ]
[-3.09184253  1.88201257 -2.2548422 ]
[ 0.00000000e+00 -2.22044605e-16 -8.88178420e-16]
(-4.440892098500626e-16+7.771561172376096e-16j)
5
[ 3.1567568   0.11839989 -1.01289564]
[ 3.1567568   0.11839989 -1.01289564]
[ 4.13002965e-14  3.85386167e-14 -3.93018951e-14]
(-2.886579864025407e-15+3.114175584073564e-14j)
3
[ 4.89821011  0.32766015 -2.78978792]
[-1.38497519  0.32766015  3.49339739]
[ 6.28318531e+00 -4.16333634e-15 -6.28318531e+00]
(1.5543122344752192e-15+2.3314683517128287e-15j)
1
[ 8.86333781  0.41905726 -1.18984867]
[-3.7030328   0.41905726 -1.18984867]
[1.25663706e+01 1.99840144e-15 2.22044605e-15]
-2.220446049250313e-15j
4
[ 1.33507136  0.07878027 -1.61986997]
[ 1.33507136  0.07878027 -1.61986997]
[ 8.21565038e-15 -4.23411306e-14 -1.53210777e-14]
(4.440892098500626e-16-4.2

In [ ]:
plt.hist2d(result.theta_rf/np.pi, result.phi_rf/np.pi, bins=100, weights=weights)
plt.xlabel(r"$\theta_{\text{rf}}$")
plt.ylabel(r"$\phi_{\text{rf}}$")

In [ ]:
from matplotlib.colors import LogNorm
plt.hist2d(result.psi_rf/np.pi, result.phi_rf/np.pi, bins=100, weights=weights, norm=LogNorm())
plt.colorbar()
plt.xlabel(r"$\psi_{\text{rf}}$")
plt.ylabel(r"$\phi_{\text{rf}}$")

In [ ]:
helicity_anges = topology.helicity_angles(global_momenta)
for (isobar, bachelor), angle in    helicity_anges.items():
    plt.figure()
    plt.hist2d(angle.theta_rf/np.pi, angle.psi_rf/np.pi, bins=100, weights=weights)
    plt.xlabel(r"$\theta$")
    plt.ylabel(r"$\psi$")
    plt.title(f"Isobar {isobar}, Bachelor {bachelor}")
    plt.colorbar()
